### PR TITLE
Allow edit response

### PR DESCRIPTION
**Pull request by shargon**
```
static Random r = new Random();
        private static void Controller_ResponseReceived(object sender, RequestHandledEventArgs e)
        {
            if (e.RequestBlock.ParsedMessages[RequestType.GetInventory] != null)
            {
                //GetMapObjectsResponse msg = (GetMapObjectsResponse)e.RequestBlock.ParsedMessages[RequestType.GetMapObjects];
                GetInventoryResponse msg = (GetInventoryResponse)e.RequestBlock.ParsedMessages[RequestType.GetInventory];

                //Random r = new Random();
                foreach (InventoryItem o in msg.InventoryDelta.InventoryItems)
                {
                    if (o.InventoryItemData != null && o.InventoryItemData.PokemonData != null)
                    {
                        o.InventoryItemData.PokemonData.PokemonId = (POGOProtos.Enums.PokemonId)r.Next(144, 151);
                    }
                }
                //foreach (MapCell o in msg.MapCells)
                //{
                //    if (o.Forts != null && o.Forts.Count > 0)
                //    {
                //        o.Forts[0].GuardPokemonCp = 69;
                //        o.Forts[0].GuardPokemonId = POGOProtos.Enums.PokemonId.Mewtwo;
                //        o.Forts[0].Sponsor = POGOProtos.Map.Fort.FortSponsor.Mcdonalds;
                //    }
                //}
            }

            // Update log
            _apiLog.Add(e);

            Console.WriteLine("Response Block -");
            foreach (var responsePair in e.ResponseBlock.ParsedMessages)
            {
                Console.WriteLine("  " + responsePair.Key);
            }
        }
```

### CODE REVIEW

**Comment by MarlonColhado** [comment]
is possible modify the requests too? 

EDIT: 
I'm trying to falsify my position through the proxy by modifying the latitude and longitude.
To show Pokemons, pokestops, ... in blocked countries or regions.

**Comment by cstrachan88** [comment]
I'm trying to keep the requests and responses strictly read only so nothing gets flagged by the servers, so I'm a little hesitant to add this yet. Can you check if subsequent requests send these modified ids or not?

**Comment by shargon** [comment]
Yes, is possible edit the request (but need change the source)

**Comment by MarlonColhado** [comment]
Thanks for the reply, I got it. I made pokestops, gym, pokemons... display in blocked countries.
Sorry for my english.

Thank you for your help!

**Comment by RollTideDG** [comment]
Thanks for this. I was able to inject the response. Now I have the response change all my poke's nicknames to their IV values.

**Pull request closed without merging**
